/**
 * Escalation: a CONFIRMED oracle callback turns a static hypothesis into
 * evidence, and the finding has to say so.
 *
 * ## Why this module exists at all
 *
 * The static analyzer and the live scanner produce entirely separate
 * structures. `runAudit()` builds `AuditResult.findings` from files;
 * `runLiveScan()` builds `LiveAuditResult.probes` from a running server;
 * neither knows the other exists. Until now they met only in
 * report.ts's renderer, and that was the right call while the live pass
 * changed nothing about a finding — cross-referencing for *display* keeps
 * the static contract clean (see types.ts).
 *
 * A confirmed callback breaks that arrangement, because it is not a
 * display concern. If a probe proves a field is injectable, then the
 * severity of that field's finding is wrong, the score computed from it is
 * wrong, and `--fail-on` gates on it are wrong — in `--json` output as much
 * as in the Markdown. So escalation has to happen to the result, before
 * anything renders or scores it, which is what this module does.
 *
 * ## The join key
 *
 * There is already one, and it is exact rather than heuristic. A static
 * finding on a field carries
 * `jsonPath = tools["<toolName>"].inputSchema.properties.<path>`; a probe
 * carries `toolName` and `fieldPath`. report.ts has parsed that pairing
 * since the STATIC-ONLY section was written. Two properties make it safe
 * to key severity off it rather than only display:
 *
 *   - Both sides are generated by palar from the same tool name, so
 *     there is no naming-convention mismatch to absorb.
 *   - `classifyExecutionAdjacentFields()` probes top-level properties
 *     only, and for a top-level property IV-001's `path` is exactly the
 *     property name. Nested fields (`config.command`) get a dotted path
 *     that no probe can ever produce, so they simply never match — which
 *     is correct, because they are never probed.
 *
 * The one case the key cannot cover is a confirmed probe with no finding
 * at that location. That should be impossible (probe selection and IV-001
 * share `matchesSensitiveKeyword` + `isConstrained`), but "impossible" is
 * doing load-bearing work there, and the failure mode is the worst one
 * available: a proven, callback-confirmed injection silently absent from
 * the findings list. So that case synthesizes a finding rather than
 * dropping it.
 */
import type { AuditResult, Finding } from "../core/types.js";
import { computeScore } from "../core/compliance.js";
import type { LiveAuditResult, LiveProbeResult } from "./types.js";

const CONFIRMED_RULE_ID = "IV-101";

/** `tools["x"].inputSchema.properties.y` → the (tool, field) pair it names. */
function parseToolFieldPath(
  jsonPath: string | undefined
): { toolName: string; fieldPath: string } | null {
  if (!jsonPath) return null;
  const m = /^tools\["([^"]+)"\]\.inputSchema\.properties\.(.+)$/.exec(jsonPath);
  return m ? { toolName: m[1]!, fieldPath: m[2]! } : null;
}

function probeKey(toolName: string, fieldPath: string): string {
  return `${toolName}::${fieldPath}`;
}

function describeCallback(probe: LiveProbeResult): string {
  const at = probe.callback?.receivedAt ?? "unknown time";
  const from = probe.callback?.remoteAddress ?? "unknown address";
  return `nonce ${probe.nonce} received at ${at} from ${from}`;
}

/**
 * Rewrites a static finding into its confirmed form.
 *
 * The wording is replaced wholesale rather than annotated, because the
 * static text is explicitly tentative ("this is a hypothesis... not an
 * observation of its behavior") and leaving that language on a critical
 * finding would be self-contradicting. The original ruleId is preserved in
 * the detail so the provenance is not lost.
 */
function confirmFinding(finding: Finding, probe: LiveProbeResult): Finding {
  const kind = probe.kind === "ssrf" ? "server-side request forgery" : "command injection";
  return {
    ...finding,
    ruleId: CONFIRMED_RULE_ID,
    severity: "critical",
    title: `CONFIRMED ${kind} via "${probe.toolName}.${probe.fieldPath}"`,
    detail:
      `A crafted payload was sent to the live tool "${probe.toolName}" over a real MCP ` +
      `connection in field "${probe.fieldPath}", and an out-of-band callback carrying that ` +
      `probe's unique nonce arrived at palar's listener: ${describeCallback(probe)}. ` +
      `The target — directly, or via a command it ran — reached back to an address it was ` +
      `given only inside the payload. This is not inferred from the schema: it supersedes ` +
      `the static ${finding.ruleId} hypothesis on the same field, which is now settled. ` +
      `Payload sent: ${probe.payload}`,
    remediation:
      `Stop passing "${probe.fieldPath}" to whatever interprets it. This field is confirmed ` +
      `to reach an interpreter or an outbound request on the running server, so a schema ` +
      `constraint is defence in depth and not a fix — the handler is where the value has to ` +
      `be neutralized.`,
  };
}

/** The finding synthesized when a confirmed probe has no static finding to escalate. */
function orphanConfirmedFinding(probe: LiveProbeResult, file: string): Finding {
  const kind = probe.kind === "ssrf" ? "server-side request forgery" : "command injection";
  return {
    ruleId: CONFIRMED_RULE_ID,
    pillar: "schema-integrity",
    severity: "critical",
    title: `CONFIRMED ${kind} via "${probe.toolName}.${probe.fieldPath}"`,
    detail:
      `A crafted payload sent to the live tool "${probe.toolName}" in field ` +
      `"${probe.fieldPath}" produced an out-of-band callback: ${describeCallback(probe)}. ` +
      `No static finding existed on this field to escalate — the static rules and the probe ` +
      `classifier disagreed about whether it was worth examining, and the probe was right. ` +
      `Reported directly so a confirmed result is never lost to that disagreement. ` +
      `Payload sent: ${probe.payload}`,
    location: {
      file,
      jsonPath: `tools["${probe.toolName}"].inputSchema.properties.${probe.fieldPath}`,
    },
    remediation:
      `Neutralize "${probe.fieldPath}" in the handler for "${probe.toolName}". Separately, ` +
      `this field produced a confirmed callback while the static rules said nothing about ` +
      `it, which is worth investigating on its own.`,
    complianceRefs: ["OWASP MCP05:2025 - Command Injection & Execution"],
  };
}

/**
 * Applies every confirmed probe across every scanned server to a static
 * result, returning a NEW result with those findings escalated to critical
 * and the score recomputed.
 *
 * Cumulative across servers on purpose: the static findings are global to
 * the discovered file set (a tool name is not scoped to one server config),
 * so escalating per server would make the same finding critical in one
 * report and medium in the next from the same run.
 *
 * Only `confirmed` escalates, and nothing else moves a severity in either
 * direction. `rejected` is deliberately untouched — the target answered
 * with an error, and that single boolean spans a handler refusal, a bounce
 * on a rule the schema never declared, and an injected command that ran
 * and exited nonzero. Downgrading on it would be reading a successful
 * injection as a clean result. `not-tested` is untouched for the opposite
 * reason: the call never reached the field, so there is no observation to
 * act on at all, and the static hypothesis is left standing exactly as the
 * static pass wrote it.
 */
export function escalateConfirmedFindings(
  staticResult: AuditResult,
  liveResults: LiveAuditResult[]
): AuditResult {
  const confirmedByField = new Map<string, LiveProbeResult>();
  for (const live of liveResults) {
    for (const probe of live.probes) {
      if (probe.status !== "confirmed") continue;
      // First confirmation wins; a second callback on the same field says
      // nothing the first did not.
      const key = probeKey(probe.toolName, probe.fieldPath);
      if (!confirmedByField.has(key)) confirmedByField.set(key, probe);
    }
  }

  if (confirmedByField.size === 0) return staticResult;

  const matched = new Set<string>();
  const findings = staticResult.findings.map((finding) => {
    const pair = parseToolFieldPath(finding.location.jsonPath);
    if (!pair) return finding;
    const key = probeKey(pair.toolName, pair.fieldPath);
    const probe = confirmedByField.get(key);
    if (!probe) return finding;
    matched.add(key);
    return confirmFinding(finding, probe);
  });

  for (const [key, probe] of confirmedByField) {
    if (matched.has(key)) continue;
    findings.push(
      orphanConfirmedFinding(probe, staticResult.findings[0]?.location.file ?? "<live server>")
    );
  }

  return {
    ...staticResult,
    findings,
    // Recomputed, not adjusted: a critical weighs 50 against a medium's 15,
    // and a score carried over from before escalation would understate a
    // result palar has now actually proven.
    score: computeScore(findings),
  };
}
